from lib import *  # noqa: F401,F403

admin = entrar("admin", CLAVE_TEMPORAL)
admin.api("POST", "/auth/change-password", {"currentPassword": CLAVE_TEMPORAL, "newPassword": "AdminPersonal2026"})
admin = entrar("admin", "AdminPersonal2026")
ADMIN_ID = int(sql("select id from usuarios where \"user\" = 'admin'"))

print("=== Altas ===")
jefa = usuario(admin, "jefa", ["personal", "pos"], "VENDEDOR")
verificar("El administrador da de alta a quien gestiona el personal", jefa.api("GET", "/personal")[0] == 200)
st, r = admin.api("POST", "/personal", {"name": "X", "user": "rolraro", "pass": "Temporal123", "role": "SUPERUSUARIO", "modules": ["pos"]})
verificar("Un rol inexistente → 400 (no un error del servidor)", st == 400 and "Rol no válido" in r.get("error", ""), (st, r))
st, r = admin.api("POST", "/personal", {"name": "X", "user": "sinmodulo", "pass": "Temporal123", "role": "VENDEDOR", "modules": ["farmacia"]})
verificar("Un módulo que la empresa no tiene → 400", st == 400 and "no están disponibles" in r.get("error", ""), (st, r))
st, r = admin.api("POST", "/personal", {"name": "Jefa", "user": "JEFA2", "pass": "123", "role": "VENDEDOR"})
verificar("Clave débil → 400", st == 400, (st, r))
st, r = jefa.api("POST", "/personal", {"name": "Nuevo Vendedor", "user": "nuevo", "pass": "Temporal123", "role": "VENDEDOR", "modules": ["pos"]})
verificar("Quien gestiona el personal da de alta vendedores", st == 201 and r["role"] == "VENDEDOR", (st, r))
NUEVO = r["id"]

print("\n=== Sin ser administrador no se llega a administrador ===")
st, r = jefa.api("POST", "/personal", {"name": "Otro Admin", "user": "otroadmin", "pass": "Temporal123", "role": "ADMINISTRADOR"})
verificar("No crea administradores → 403", st == 403 and r.get("codigo") == "PERSONAL_SIN_PERMISO", (st, r))
jefa_id = int(sql("select id from usuarios where \"user\" = 'jefa'"))
st, r = jefa.api("PUT", f"/personal/{jefa_id}", {"name": "Jefa", "user": "jefa", "role": "ADMINISTRADOR"})
verificar("No se asciende a sí misma → 403", st == 403, (st, r))
st, r = jefa.api("PUT", f"/personal/{ADMIN_ID}", {"name": "Administrador", "user": "admin", "pass": "TomadoPorJefa1"})
verificar("No restablece la clave del administrador → 403", st == 403, (st, r))
verificar("…y la clave del administrador sigue siendo la suya", entrar("admin", "AdminPersonal2026").api("GET", "/auth/me")[0] == 200)
st, r = jefa.api("DELETE", f"/personal/{ADMIN_ID}")
verificar("No elimina al administrador", st in (400, 403), (st, r))
st, r = jefa.api("PUT", f"/personal/{NUEVO}", {"name": "Nuevo Vendedor", "user": "nuevo", "role": "CAJERO", "modules": ["caja"]})
verificar("Sí cambia el rol de un empleado que no es administrador", st == 200 and r["role"] == "CAJERO", (st, r))
st, r = admin.api("POST", "/personal", {"name": "Segunda Admin", "user": "admin2", "pass": "Temporal123", "role": "ADMINISTRADOR"})
verificar("El administrador sí crea administradores", st == 201 and r["role"] == "ADMINISTRADOR", (st, r))

print("\n=== Cambios y bajas ===")
st, r = admin.api("PUT", f"/personal/{NUEVO}", {"name": "Nuevo Vendedor", "user": "jefa"})
verificar("No toma el nombre de usuario de otro → 400", st == 400 and "ya está siendo usado" in r.get("error", ""), (st, r))
st, r = admin.api("PUT", f"/personal/{ADMIN_ID}", {"name": "Administrador", "user": "admin", "active": False})
verificar("El administrador principal no se desactiva", st == 400, (st, r))
st, r = admin.api("DELETE", f"/personal/{NUEVO}")
verificar("Se elimina a quien no tiene movimientos", st == 200, (st, r))
verificar("…y queda en la auditoría", sql("select count(*) from audit_logs where action = 'USER_DELETED'") == "1")
st, r = admin.api("DELETE", "/personal/99999")
verificar("Usuario inexistente → 404", st == 404, (st, r))

resumen()
